var c1 = [
  {
    "name":"Barbarian",
    "hitDie":10,
    "hpPerLvl":6,
    "scoreMinimum":"Constitution 13",
    "otherRequirement":"None.",
    "table":"<colgroup><col style='width:10%;'><col style='width:10%;'><col style='width:60%;'><col style='width:10%;'><col style='width:10%;'></colgroup><tr><th>Level</th><th>Proficiency Bonus</th><th>Features</th><th>Rages</th><th>Rage Damage</th></tr><tr><td>1st</td><td>+2</td><td><a href='#Rage'>Rage</a>, <a href='#UnarmoredDefense'>Unarmored Defense</a></td><td>2</td><td>+2</td></tr><tr><td>2nd</td><td>+2</td><td><a href='#DangerSense'>Danger Sense</a>, <a href='#RecklessAttack'>Reckless Attack</a></td><td>2</td><td>+2</td></tr><tr><td>3rd</td><td>+2</td><td><a href='#PrimalPath'>Primal Path</a></td><td>3</td><td>+2</td></tr><tr><td>4th</td><td>+2</td><td>—</td><td>3</td><td>+2</td></tr><tr><td>5th</td><td>+3</td><td><a href='#ExtraAttack'>Extra Attack</a>, <a href='#FastMovement'>Fast Movement</a></td><td>3</td><td>+2</td></tr><tr><td>6th</td><td>+3</td><td><a href='#PathFeature1'>Path Feature</a></td><td>4</td><td>+2</td></tr><tr><td>7th</td><td>+3</td><td><a href='#FeralInstinct'>Feral Instinct</a></td><td>4</td><td>+2</td></tr><tr><td>8th</td><td>+3</td><td>—</td><td>4</td><td>+2</td></tr><tr><td>9th</td><td>+4</td><td><a href='#BrutalCritical1'>Brutal Critical (1 die)</a></td><td>4</td><td>+3</td></tr><tr><td>10th</td><td>+4</td><td><a href='#PathFeature2'>Path Feature</a></td><td>4</td><td>+3</td></tr><tr><td>11th</td><td>+4</td><td><a href='#RelentlessRage'>Relentless Rage</a></td><td>4</td><td>+3</td></tr><tr><td>12th</td><td>+4</td><td>—</td><td>5</td><td>+3</td></tr><tr><td>13th</td><td>+5</td><td><a href='#BrutalCritical2'>Brutal Critical (2 dice)</a></td><td>5</td><td>+3</td></tr><tr><td>14th</td><td>+5</td><td><a href='#PathFeature3'>Path Feature</a></td><td>5</td><td>+3</td></tr><tr><td>15th</td><td>+5</td><td><a href='#PersistentRage'>Persistent Rage</a></td><td>5</td><td>+3</td></tr><tr><td>16th</td><td>+5</td><td>—</td><td>5</td><td>+4</td></tr><tr><td>17th</td><td>+6</td><td><a href='#BrutalCritical3'>Brutal Critical (3 dice)</a></td><td>6</td><td>+4</td></tr><tr><td>18th</td><td>+6</td><td><a href='#IndomitableMight'>Indomitable Might</a></td><td>6</td><td>+4</td></tr><tr><td>19th</td><td>+6</td><td>—</td><td>6</td><td>+4</td></tr><tr><td>20th</td><td>+6</td><td><a href='#PrimalChampion'>Primal Champion</a></td><td>Unlimited</td><td>+4</td></tr>",
    "subclassList":"<tr><th>Primal Paths</th></tr><tr><td><a href='#' onclick='pathDisplay(0)'>Ancestral Guardian</a></td></tr><tr><td><a href='#' onclick='pathDisplay(1)'>Berserker</a></td></tr><tr><td><a href='#' onclick='pathDisplay(2)'>Storm Herald</a></td></tr><tr><td><a href='#' onclick='pathDisplay(3)'>Totem Warrior</a></td></tr><tr><td><a href='#' onclick='pathDisplay(4)'>Zealot</a></td></tr>",
    "lvl1":"<h2 id='Rage'>Rage</h2><hr><p>In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action. While raging, you gain the following benefits if you aren't wearing heavy armor:</p><ul><li>You have advantage on Strength checks and Strength saving throws.</li><li>When you make a melee weapon attack using Strength, you gain a +2 bonus to the damage roll. This bonus increases as you level.</li><li>You have resistance to bludgeoning, piercing, and slashing damage.</li></ul><p>If you are able to cast spells, you can't cast them or concentrate on them while raging.</p><p>Your rage lasts for 1 minute. It ends early if you are knocked unconscious or if your turn ends and you haven't attacked a hostile creature since your last turn or taken damage since then. You can also end your rage on your turn as a bonus action.</p><p>Once you have raged the maximum number of times for your barbarian level, you must finish a long rest before you can rage again. You may rage 2 times at 1st level, 3 at 3rd, 4 at 6th, 5 at 12th, and 6 at 17th.</p><h2 id='UnarmoredDefense'>Unarmored Defense</h2><hr><p>While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit.</p>",
    "lvl2":"<h2 id='DangerSense'>Danger Sense</h2><hr><p>At 2nd level, you gain an uncanny sense of when things nearby aren't as they should be, giving you an edge when you dodge away from danger. You have advantage on Dexterity saving throws against effects that you can see, such as traps and spells. To gain this benefit, you can't be blinded, deafened, or incapacitated.</p><h2 id='RecklessAttack'>Reckless Attack</h2><hr><p>Starting at 2nd level, you can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly. Doing so gives you advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn.</p>",
    "lvl3":"<h2 id='PrimalPath'>Primal Path</h2><hr><p>At 3rd level, you choose a path that shapes the nature of your rage from the list of available paths. Your choice grants you features at 3rd level and again at 6th, 10th, and 14th levels.</p>",
    "lvl4":"",
    "lvl5":"<h2 id='ExtraAttack'>Extra Attack</h2><hr><p>Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.</p><h2 id='FastMovement'>Fast Movement</h2><hr><p>Starting at 5th level, your speed increases by 3 meters while you aren't wearing heavy armor.</p>",
    "lvl6":"<h2 id='PathFeature1'>Path Feature</h2><hr><p>At 6th level, you gain a feature from your Primal Path.</p>",
    "lvl7":"<h2 id='FeralInstinct'>Feral Instinct</h2><hr><p>By 7th level, your instincts are so honed that you have advantage on initiative rolls.</p><p>Additionally, if you are surprised at the beginning of combat and aren't incapacitated, you can act normally on your first turn, but only if you enter your rage before doing anything else on that turn.</p>",
    "lvl8":"",
    "lvl9":"<h2 id='BrutalCritical1'>Brutal Critical (1 die)</h2><hr><p>Beginning at 9th level, you can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack.</p><p>This increases to two additional dice at 13th level and three additional dice at 17th level.</p>",
    "lvl10":"<h2 id='PathFeature2'>Path Feature</h2><hr><p>At 10th level, you gain a feature from your Primal Path.</p>",
    "lvl11":"<h2 id='RelentlessRage'>Relentless Rage</h2><hr><p>Starting at 11th level, your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while you're raging and don't die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead.</p><p>Each time you use this feature after the first, the DC increases by 5. When you finish a short or long rest, the DC resets to 10.</p>",
    "lvl12":"",
    "lvl13":"<h2 id='BrutalCritical2'>Brutal Critical (2 dice)</h2><hr><p>At 13th level, you can roll two additional weapon damage dice when determining the extra damage for a critical hit with a melee attack.</p><p>This increases to three additional dice at 17th level.</p>",
    "lvl14":"<h2 id='PathFeature3'>Path Feature</h2><hr><p>At 14th level, you gain a feature from your Primal Path.</p>",
    "lvl15":"<h2 id='PersistentRage'>Persistent Rage</h2><hr><p>Beginning at 15th level, your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it.</p>",
    "lvl16":"",
    "lvl17":"<h2 id='BrutalCritical3'>Brutal Critical (3 dice)</h2><hr><p>At 17th level, you can roll three additional weapon damage dice when determining the extra damage for a critical hit with a melee attack.</p>",
    "lvl18":"<h2 id='IndomitableMight'>Indomitable Might</h2><hr><p>Beginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total.</p>",
    "lvl19":"",
    "lvl20":"<h2 id='PrimalChampion'>Primal Champion</h2><hr><p>At 20th level, you embody the power of the wilds. Your Strength and Constitution scores, along with their maximum, increase by 4. </p>",

  },
  {
    "name":"Bard",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Charisma 13",
    "otherRequirement":"Proficiency with the Performance skill.",
    "table":"<colgroup><col style='width:10%;'><col style='width:10%;'><col style='width:30%;'><col style='width:8%;'><col style='width:8%;'></colgroup><tr><th colspan='5'></th><th colspan='9'><i>Spell Slots per Spell Level</i></th></tr><tr><th>Level</th><th>Proficiency Bonus</th><th>Features</th><th>Cantrips Known</th><th>Spells Known</th><th>1st</th><th>2nd</th><th>3rd</th><th>4th</th><th>5th</th><th>6th</th><th>7th</th><th>8th</th><th>9th</th></tr><tr><td>1st</td><td>+2</td><td><a href='#BardicInspiration1'>Bardic Inspiration (d6)</a>, <a href='#Spellcasting'>Spellcasting</a></td><td>2</td><td>4</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>2nd</td><td>+2</td><td><a href='#JackofAllTrades'>Jack of All Trades</a>, <a href='#SongofRest1'>Song of Rest (d6)</a></td><td>2</td><td>5</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>3rd</td><td>+2</td><td><a href='#BardCollege'>Bard College</a></td><td>2</td><td>6</td><td>4</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>4th</td><td>+2</td><td>—</td><td>3</td><td>7</td><td>4</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>5th</td><td>+3</td><td><a href='#BardicInspiration2'>Bardic Inspiration (d8)</a></td><td>3</td><td>8</td><td>4</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>6th</td><td>+3</td><td><a href='#Countercharm'>Countercharm</a>, <a href='#BardCollegeFeature1'>Bard College Feature</a></td><td>3</td><td>9</td><td>4</td><td>3</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>7th</td><td>+3</td><td>—</td><td>3</td><td>10</td><td>4</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>8th</td><td>+3</td><td>—</td><td>3</td><td>11</td><td>4</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>9th</td><td>+4</td><td><a href='#SongofRest2'>Song of Rest (1d8)</a></td><td>3</td><td>12</td><td>4</td><td>3</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>10th</td><td>+4</td><td><a href='#BardicInspiration3'>Bardic Inspiration (d10)</a>, <a href='#Expertise2'>Expertise</a>, <a href='#MagicalSecrets1'>Magical Secrets</a></td><td>4</td><td>14</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>11th</td><td>+4</td><td>—</td><td>4</td><td>15</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>12th</td><td>+4</td><td>—</td><td>4</td><td>15</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>13th</td><td>+5</td><td><a href='#SongofRest3'>Song of Rest (d10)</a></td><td>4</td><td>16</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>14th</td><td>+5</td><td><a href='#MagicalSecrets2'>Magical Secrets</a>, <a href='#BardCollegeFeature2'>Bard College Feature</a></td><td>4</td><td>18</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>15th</td><td>+5</td><td><a href='#BardicInspiration4'>Bardic Inspiration (d12)</a></td><td>4</td><td>19</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>16th</td><td>+5</td><td>—</td><td>4</td><td>19</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>17th</td><td>+6</td><td><a href='#SongofRest4'>Song of Rest (d12)</a></td><td>4</td><td>20</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>18th</td><td>+6</td><td><a href='#MagicalSecrets3'>Magical Secrets</a></td><td>4</td><td>22</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>19th</td><td>+6</td><td>—</td><td>4</td><td>22</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td></tr><tr><td>20th</td><td>+6</td><td><a href='#SuperiorInspiration'>Superior Inspiration</a></td><td>4</td><td>22</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>2</td><td>1</td><td>1</td></tr>",
    "subclassList":"<tr><th>Bard Colleges</th></tr><tr><td><a href='#' onclick='collegeDisplay(0)'>Eloquence</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(1)'>Glamour</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(2)'>Lore</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(3)'>Swords</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(4)'>Valor</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(5)'>Whispers</a></td></tr>",
    "lvl1":"<h2 id='BardicInspiration1'>Bardic Inspiration (d6)</h2><hr><p>You can inspire others through stirring words or music. To do so, you use a bonus action on your turn to choose one creature other than yourself within 20 meters of you who can hear you. That creature gains one Bardic Inspiration die, a d6.</p><p>Once within the next 10 minutes, the creature can roll the die and add the number rolled to one ability check, attack roll, or saving throw it makes. The creature can wait until after it rolls the d20 before deciding to use the Bardic Inspiration die, but must decide before the DM says whether the roll succeeds or fails. Once the Bardic Inspiration die is rolled, it is lost. A creature can have only one Bardic Inspiration die at a time.</p><p>You can use this feature a number of times equal to your Charisma modifier (a minimum of once). You regain any expended uses when you finish a long rest.</p><p>Your Bardic Inspiration die changes when you reach certain levels in this class. The die becomes a d8 at 5th level, a d10 at 10th level, and a d12 at 15th level.</p><h2 id='Spellcasting'>Spellcasting</h2><hr><p>You have learned to untangle and reshape the fabric of reality in harmony with your wishes and music. Your spells are part of your vast repertoire, magic that you can tune to different situations.</p><h3>Cantrips</h3><p>You know two cantrips of your choice from the bard spell list. You learn additional bard cantrips of your choice at higher levels, learning a 3rd cantrip at 4th level and a 4th at 10th level.</p><h3>Spell Slots</h3><p>The Bard table shows how many spell slots you have to cast your bard spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell's level or higher. You regain all expended spell slots when you finish a long rest.</p><p>For example, if you know the 1st-level spell cure wounds and have a 1st-level and a 2nd-level spell slot available, you can cast cure wounds using either slot.</p><h3>Spells Known of 1st Level and Higher</h3><p>You know four 1st-level spells of your choice from the bard spell list.</p><p>You learn an additional bard spell of your choice at each level except 12th, 16th, 19th, and 20th. Each of these spells must be of a level for which you have spell slots. For instance, when you reach 3rd level in this class, you can learn one new spell of 1st or 2nd level.</p><p>Additionally, when you gain a level in this class, you can choose one of the bard spells you know and replace it with another spell from the bard spell list, which also must be of a level for which you have spell slots.</p><h3>Spellcasting Ability</h3><p>Charisma is your spellcasting ability for your bard spells. Your magic comes from the heart and soul you pour into the performance of your music or oration. You use your Charisma whenever a spell refers to your spellcasting ability. In addition, you use your Charisma modifier when setting the saving throw DC for a bard spell you cast and when making an attack roll with one.</p><ul> <li><strong>Spell save DC</strong> = 8 + your proficiency bonus + your Charisma modifier.</li><li><strong>Spell attack modifier</strong> = your proficiency bonus + your Charisma modifier</p></li></ul><h3>Ritual Casting</h3><p>You can cast any bard spell you know as a ritual if that spell has the ritual tag.</p><h3>Spellcasting Focus</h3><p>You can use a musical instrument as a spellcasting focus for your bard spells.</p>",
    "lvl2":"<h2 id='JackofAllTrades'>Jack of All Trades</h2><hr><p>Starting at 2nd level, you can add half your proficiency bonus, rounded down, to any ability check you make that doesn't already include your proficiency bonus.</p><h2 id='SongofRest1'>Song of Rest (d6)</h2><hr><p>Beginning at 2nd level, you can use soothing music or oration to help revitalize your wounded allies during a short rest. If you or any friendly creatures who can hear your performance regain hit points by spending Hit Dice at the end of the short rest, each of those creatures regains an extra 1d6 hit points.</p><p>The extra hit points increase when you reach certain levels in this class: to 1d8 at 9th level, to 1d10 at 13th level, and to 1d12 at 17th level.</p>",
    "lvl3":"<h2 id='BardCollege'>Bard College</h2><hr><p>At 3rd level, you delve into the advanced techniques of a bard college of your choice from the list of available colleges. Your choice grants you features at 3rd level and again at 6th and 14th level.</p><h2 id='Expertise1'>Expertise</h2><hr><p>At 3rd level, choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.</p><p>At 10th level, you can choose another two skill proficiencies to gain this benefit.</p>",
    "lvl4":"",
    "lvl5":"<h2 id='BardicInspiration2'>Bardic Inspiration (d8)</h2><hr><p>At 5th level, your Bardic Inspiration die changes to a d8.</p>",
    "lvl6":"<h2 id='Countercharm'>Countercharm</h2><hr><p>At 6th level, you gain the ability to use musical notes or words of power to disrupt mind-influencing effects. As an action, you can start a performance that lasts until the end of your next turn. During that time, you and any friendly creatures within 10 meters of you have advantage on saving throws against being frightened or charmed. A creature must be able to hear you to gain this benefit. The performance ends early if you are incapacitated or silenced or if you voluntarily end it (no action required).</p><h2 id='BardCollegeFeature1'>Bard College Feature</h2><hr><p>At 6th level, you gain a feature from your Bard College.</p>",
    "lvl7":"<h2 id='FontofInspiration'>Font of Inspiration</h2><hr><p>Starting at 7th level, you gain back one expended use of Bardic Inspiration when you finish a short rest.</p>",
    "lvl8":"",
    "lvl9":"<h2 id='SongofRest2'>Song of Rest (d8)</h2><hr><p>At 9th level, the extra hit points gained from Song of Rest increases to 1d8.</p>",
    "lvl10":"<h2 id='BardicInspiration3'>Bardic Inspiration (d10)</h2><hr><p>At 10th level, your Bardic Inspiration die changes to a d10.</p><h2 id='Expertise2'>Expertise</h2><hr><p>At 10th level, you can choose another two skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.</p><h2 id='MagicalSecrets1'>Magical Secrets</h2><hr><p>By 10th level, you have plundered magical knowledge from a wide spectrum of disciplines. Choose two spells from any classes, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip.</p><p>The chosen spells count as bard spells for you and are included in the number in the Spells Known column of the Bard table.</p><p>You learn two additional spells from any classes at 14th level and again at 18th level.</p>",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"<h2 id='SongofRest3'>Song of Rest (d10)</h2><hr><p>At 13th level, the extra hit points gained from Song of Rest increases to 1d10.</p>",
    "lvl14":"<h2 id='MagicalSecrets2'>Magical Secrets</h2><hr><p>At 14th level, choose two additional spells from any classes, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip.</p><p>The chosen spells count as bard spells for you and are included in the number in the Spells Known column of the Bard table.</p><h2 id='BardCollegeFeature2'>Bard College Feature</h2><hr><p>At 14th level, you gain a feature from your Bard College.</p>",
    "lvl15":"<h2 id='BardicInspiration4'>Bardic Inspiration</h2><hr><p>At 15th level, your Bardic Inspiration die changes to a d12.</p>",
    "lvl16":"",
    "lvl17":"<h2 id='SongofRest4'>Song of Rest (d12)</h2><hr><p>At 17th level, the extra hit points gained from Song of Rest increases to 1d12.</p>",
    "lvl18":"<h2 id='MagicalSecrets3'>Magical Secrets</h2><hr><p>At 18th level, choose two additional spells from any class, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip.</p><p>The chosen spells count as bard spells for you and are included in the number in the Spells Known column of the Bard table.</p>",
    "lvl19":"",
    "lvl20":"<h2 id='SuperiorInspiration'>Superior Inspiration</h2><hr><p>At 20th level, your inspiring nature fully manifests. When a creature uses your Bardic Inspiration die, the lowest number they can roll on it is equal to your Charisma modifier.</p>",
  },
  {
    "name":"Cleric",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Wisdom 13",
    "otherRequirement":"Proficiency with the Divina skill.",
    "table":"<colgroup><col style='width:10%;'><col style='width:10%;'><col style='width:38%;'><col style='width:8%;'></colgroup><tr><th colspan='4'></th><th colspan='9'><i>Spell Slots per Spell Level</i></th></tr><tr><th>Level</th><th>Proficiency Bonus</th><th>Features</th><th>Cantrips Known</th><th>1st</th><th>2nd</th><th>3rd</th><th>4th</th><th>5th</th><th>6th</th><th>7th</th><th>8th</th><th>9th</th></tr><tr><td>1st</td><td>+2</td><td><a href='#Spellcasting'>Spellcasting</a>, <a href='#DivineDomain'>Divine Domain</a></td><td>2</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>2nd</td><td>+2</td><td><a href='#ChannelDivinity1'>Channel Divinity (1/Long Rest)</a>, <a href='#DivineDomainFeature1'>Divine Domain Feature</a></td><td>2</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>3rd</td><td>+2</td><td>—</td><td>2</td><td>4</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>4th</td><td>+2</td><td>—</td><td>3</td><td>4</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>5th</td><td>+3</td><td><a href='#Orison1'>Orison</a></td><td>3</td><td>4</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>6th</td><td>+3</td><td><a href='#ChannelDivinity2'>Channel Divinity (2/Long Rest)</a>, <a href='#DivineDomainFeature2'>Divine Domain Feature</a></td><td>3</td><td>4</td><td>3</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>7th</td><td>+3</td><td>—</td><td>3</td><td>4</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>8th</td><td>+3</td><td><a href='#DivineDomainFeature3'>Divine Domain Feature</a>, <a href='#Orison2'>Additional Orison</a></td><td>3</td><td>4</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>9th</td><td>+4</td><td>—</td><td>3</td><td>4</td><td>3</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>10th</td><td>+4</td><td><a href='#DivineIntervention'>Divine Intervention</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>11th</td><td>+4</td><td><a href='#Orison3'>Additional Orison</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>12th</td><td>+4</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>13th</td><td>+5</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>14th</td><td>+5</td><td><a href='#Orison4'>Additional Orison</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>15th</td><td>+5</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>16th</td><td>+5</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>17th</td><td>+6</td><td><a href='#Orison5'>Additional Orison</a>, <a href='#DivineDomainFeature4'>Divine Domain Feature</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>18th</td><td>+6</td><td><a href='#ChannelDivinity3'>Channel Divinity (3/Long Rest)</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>19th</td><td>+6</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td></tr><tr><td>20th</td><td>+6</td><td><a href='#DivineInterventionImprovement'>Divine Intervention Improvement</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>2</td><td>1</td><td>1</td></tr>",
    "subclassList":"<colgroup><col style='width:50%'><col style='width:50%'></colgroup><tr><th colspan='2'>Divine Domains</th></tr><tr><td><a href='#' onclick='domainDisplay(0)'>Arcana</a></td><td><a href='#' onclick='domainDisplay(10)'>Luck</a></td></tr><tr><td><a href='#' onclick='domainDisplay(1)'>Death</a></td><td><a href='#' onclick='domainDisplay(11)'>Nature</a></td></tr><tr><td><a href='#' onclick='domainDisplay(2)'>Destruction</a></td><td><a href='#' onclick='domainDisplay(12)'>Order</a></td></tr><tr><td><a href='#' onclick='domainDisplay(3)'>Forge</a></td><td><a href='#' onclick='domainDisplay(13)'>Secrets</a></td></tr><tr><td><a href='#' onclick='domainDisplay(4)'>Grave</a></td><td><a href='#' onclick='domainDisplay(14)'>Tempest</a></td></tr><tr><td><a href='#' onclick='domainDisplay(5)'>Greed</a></td><td><a href='#' onclick='domainDisplay(15)'>Time</a></td></tr><tr><td><a href='#' onclick='domainDisplay(6)'>Knowledge</a></td><td><a href='#' onclick='domainDisplay(16)'>Travel</a></td></tr><tr><td><a href='#' onclick='domainDisplay(7)'>Life</a></td><td><a href='#' onclick='domainDisplay(17)'>Trickery</a></td></tr><tr><td><a href='#' onclick='domainDisplay(8)'>Light</a></td><td><a href='#' onclick='domainDisplay(18)'>Valor</a></td></tr><tr><td><a href='#' onclick='domainDisplay(9)'>Love</a></td><td><a href='#' onclick='domainDisplay(19)'>War</a></td></tr>",
    "lvl1":"<h2 id='Spellcasting'>Spellcasting</h2><hr><p>As a conduit for divine power, you can cast cleric spells.</p><h3>Cantrips</h3><p>At 1st level, you know two cantrips of your choice from the cleric spell list. You learn additional cleric cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Cleric table.</p><h3>Preparing and Casting Spells</h3><p>The Cleric table shows how many spell slots you have to cast your cleric spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell's level or higher. You regain all expended spell slots when you finish a long rest.</p><p>You prepare the list of cleric spells that are available for you to cast, choosing from the cleric spell list. When you do so, choose a number of cleric spells equal to your Wisdom modifier + your cleric level (minimum of one spell). The spells must be of a level for which you have spell slots.</p><p>For example, if you are a 3rd-level cleric, you have four 1st-level and two 2nd-level spell slots. With a Wisdom of 16, your list of prepared spells can include six spells of 1st or 2nd level, in any combination. If you prepare the 1st-level spell cure wounds, you can cast it using a 1st-level or 2nd-level slot. Casting the spell doesn't remove it from your list of prepared spells.</p><p>You can change your list of prepared spells when you finish a long rest. Preparing a new list of cleric spells requires time spent in prayer and meditation: at least 1 minute per spell level for each spell on your list.</p><h3>Spellcasting Ability</h3><p>Wisdom is your spellcasting ability for your cleric spells. The power of your spells comes from your devotion to your deity. You use your Wisdom whenever a cleric spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for a cleric spell you cast and when making an attack roll with one.</p><ul><li><strong>Spell save DC</strong> = 8 + your proficiency bonus + your Wisdom modifier</li><li><strong>Spell attack modifier</strong> = your proficiency bonus + your Wisdom modifier</li></ul><h3>Ritual Casting</h3><p>You can cast a cleric spell as a ritual if that spell has the ritual tag and you have the spell prepared.</p><h3>Spellcasting Focus</h3><p>You can use a holy symbol as a spellcasting focus for your cleric spells.</p><h2 id='DivineDomain'>Divine Domain</h2><hr><p>Choose one domain related to your deity from the list of available domains. Each domain is detailed in their own feature, and each one provides examples of gods associated with it. Your choice grants you domain spells and other features when you choose it at 1st level. It also grants you additional ways to use Channel Divinity when you gain that feature at 2nd level, and additional benefits at 6th, 8th, and 17th levels.</p><p>When you choose a domain, you do not necessarily need to choose a god associated with it to worship; instead, you can choose to be devout to the ideals of the domain itself.</p><h3>Domain Spells</h3><p>Each domain has a list of spells—its domain spells—that you gain at the cleric levels noted in the domain description. Once you gain a domain spell, you always have it prepared, and it doesn't count against the number of spells you can prepare each day.</p><p>If you have a domain spell that doesn't appear on the cleric spell list, the spell is nonetheless a cleric spell for you.</p>",
    "lvl2":"<h2 id='ChannelDivinity1'>Channel Divinity (1/Long Rest)</h2><hr><p>At 2nd level, you gain the ability to channel divine energy directly from your deity, using that energy to fuel magical effects. You start with one such effect: an effect determined by your domain. Some domains grant you additional effects as you advance in levels, as noted in the domain description.</p><p>When you use your Channel Divinity, you choose which effect to create. You must then finish a short or long rest to use your Channel Divinity again.</p><p>Some Channel Divinity effects require saving throws. When you use such an effect from this class, the DC equals your cleric spell save DC.</p><p>Beginning at 6th level, you can use your Channel Divinity twice between long rests, and beginning at 18th level, you can use it three times between long rests. When you finish a long rest, you regain your expended uses.</p><h2 id='DivineDomainFeature1'>Divine Domain Feature</h2><hr><p>At 2nd level, you gain a feature from your Divine Domain.</p>",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"<h2 id='Orison1'>Orison</h2><hr><p>At 5th level, the devotion for your god or ideal grants you a minor magical effect. Such effect is known as an Orison, which you can find a list of here. When you choose an Orison, you must meet its prerequisites. You are granted an additional Orison at 8th, 11th, and 14th levels.</p><p>When you gain a level in this class, you can replace one Orison you know for another Orison you meet the prerequisites for.</p>",
    "lvl6":"<h2 id='ChannelDivinity2'>Channel Divinity (2/Long Rest)</h2><hr><p>Beginning at 6th level, you can use your Channel Divinity twice between rests.</p><h2 id='DivineDomainFeature2'>Divine Domain Feature</h2><hr><p>At 6th level, you gain a feature from your Divine Domain.</p>",
    "lvl7":"",
    "lvl8":"<h2 id='Orison2'>Additional Orison</h2><hr><p>At 8th level, you are granted an additional Orison.</p><h2 id='DivineDomainFeature3'>Divine Domain Feature</h2><hr><p>At 8th level, you gain a feature from your Divine Domain.</p>",
    "lvl9":"",
    "lvl10":"<h2 id='DivineIntervention'>Divine Intervention</h2><hr><p>Beginning at 10th level, you can call on your deity to intervene on your behalf when your need is great.</p><p>Imploring your deity's aid requires you to use your action. Describe the assistance you seek, and roll percentile dice. If you roll a number equal to or lower than your cleric level, your deity intervenes. The DM chooses the nature of the intervention; the effect of any cleric spell or cleric domain spell would be appropriate. If your deity intervenes, you can't use this feature again for 7 days. Otherwise, you can use it again after you finish a long rest.</p><p>At 20th level, your call for intervention succeeds automatically, no roll required.</p>",
    "lvl11":"<h2 id='Orison3'>Additional Orison</h2><hr><p>At 11th level, you are granted an additional Orison.</p>",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"<h2 id='Orison4'>Additional Orison</h2><hr><p>At 14th level, you are granted an additional Orison.</p>",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"<h2 id='DivineDomainFeature4'>Divine Domain Feature</h2><hr><p>At 17th level, you gain a feature from your Divine Domain.</p><h2 id='Orison5'>Additional Orison</h2><hr><p>At 17th level, you are granted an additional Orison.</p>",
    "lvl18":"<h2 id='ChannelDivinity3'>Channel Divinity (3/Long Rest)</h2><hr><p>Beginning at 18th level, you can use your Channel Divinity three times between rests.</p>",
    "lvl19":"",
    "lvl20":"<h2 id='DivineInterventionImprovement'>Divine Intervention Improvement</h2><hr><p>At 20th level, your call for intervention succeeds automatically, no roll required.</p>",
  },
  {
    "name":"Druid",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Wisdom 13",
    "otherRequirement":"Proficiency with the Prima skill.",
    "table":"<colgroup><col style='width:10%;'><col style='width:10%;'><col style='width:38%;'><col style='width:8%;'></colgroup><tr><th colspan='4'></th><th colspan='9'><i>Spell Slots per Spell Level</i></th></tr><tr><th>Level</th><th>Proficiency Bonus</th><th>Features</th><th>Cantrips Known</th><th>1st</th><th>2nd</th><th>3rd</th><th>4th</th><th>5th</th><th>6th</th><th>7th</th><th>8th</th><th>9th</th></tr><tr><td>1st</td><td>+2</td><td><a href='#Druidic'>Druidic</a>, <a href='#Spellcasting'>Spellcasting</a></td><td>2</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>2nd</td><td>+2</td><td><a href='#WildShape'>Wild Shape</a>, <a href='#DruidCircle'>Druid Circle</a></td><td>2</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>3rd</td><td>+2</td><td>—</td><td>2</td><td>4</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>4th</td><td>+2</td><td><a href='#WildShapeImprovement1'>Wild Shape Improvement</a></td><td>3</td><td>4</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>5th</td><td>+3</td><td>—</td><td>3</td><td>4</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>6th</td><td>+3</td><td><a href='#DruidCircleFeature1'>Druid Circle Feature</a></td><td>3</td><td>4</td><td>3</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>7th</td><td>+3</td><td>—</td><td>3</td><td>4</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>8th</td><td>+3</td><td><a href='#WildShapeImprovement2'>Wild Shape Improvement</a></td><td>3</td><td>4</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>9th</td><td>+4</td><td>—</td><td>3</td><td>4</td><td>3</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>10th</td><td>+4</td><td><a href='#DruidCircleFeature2'>Druid Circle Feature</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>11th</td><td>+4</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>12th</td><td>+4</td><td><a href='#WildShapeImprovement3'></a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>13th</td><td>+5</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>14th</td><td>+5</td><td><a href='#DruidCircleFeature3'>Druid Circle Feature</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>15th</td><td>+5</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>16th</td><td>+5</td><td><a href='#WildShapeImprovement4'></a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>17th</td><td>+6</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>18th</td><td>+6</td><td><a href='#TimelessBody'>Timeless Body</a>, <a href='#BeastSpells'>Beast Spells</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>19th</td><td>+6</td><td>—</td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td></tr><tr><td>20th</td><td>+6</td><td><a href='#Archdruid'>Archdruid</a></td><td>4</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>2</td><td>1</td><td>1</td></tr>",
    "subclassList":"<tr><th>Druid Circles</th></tr><tr><td><a href='#' onclick='circleDisplay(0)'>Dreams</a></td></tr><tr><td><a href='#' onclick='circleDisplay(1)'>Spores</a></td></tr><tr><td><a href='#' onclick='circleDisplay(2)'>Land</a></td></tr><tr><td><a href='#' onclick='circleDisplay(3)'>Moon</a></td></tr><tr><td><a href='#' onclick='circleDisplay(4)'>Shepard</a></td></tr>",
    "lvl1":"<h2 id='Druidic'>Druidic</h2><hr><p>You know Druidic, the secret language of druids. You can speak the language and use it to leave hidden messages. You and others who know this language automatically spot such a message. Others spot the message's presence with a successful DC 15 Wisdom (Perception) check but can't decipher it without magic.</p><h2 id='Spellcasting'>Spellcasting</h2><hr><p>Drawing on the divine essence of nature itself, you can cast spells to shape that essence to your will.</p><h3>Cantrips</h3><p>At 1st level, you know two cantrips of your choice from the druid spell list. You learn additional druid cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Druid table.</p><h3>Preparing and Casting Spells</h3><p>The Druid table shows how many spell slots you have to cast your druid spells of 1st level and higher. To cast one of these druid spells, you must expend a slot of the spell's level or higher. You regain all expended spell slots when you finish a long rest.</p>You prepare the list of druid spells that are available for you to cast, choosing from the druid spell list. When you do so, choose a number of druid spells equal to your Wisdom modifier + your druid level (minimum of one spell). The spells must be of a level for which you have spell slots.</p>For example, if you are a 3rd-level druid, you have four 1st-level and two 2nd-level spell slots. With a Wisdom of 16, your list of prepared spells can include six spells of 1st or 2nd level, in any combination. If you prepare the 1st-level spell cure wounds, you can cast it using a 1st-level or 2nd-level slot. Casting the spell doesn't remove it from your list of prepared spells.</p>You can also change your list of prepared spells when you finish a long rest. Preparing a new list of druid spells requires time spent in prayer and meditation: at least 1 minute per spell level for each spell on your list.</p><h3>Spellcasting Ability</h3><p>Wisdom is your spellcasting ability for your druid spells, since your magic draws upon your devotion and attunement to nature. You use your Wisdom whenever a spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for a druid spell you cast and when making an attack roll with one.</p><ul><li><strong>Spell save DC</strong> = 8 + your proficiency bonus + your Wisdom modifier</li><li><strong>Spell attack modifier</strong> = your proficiency bonus + your Wisdom modifier</p></li></ul><h3>Ritual Casting</h3><p>You can cast a druid spell as a ritual if that spell has the ritual tag and you have the spell prepared.</p><h3>Spellcasting Focus</h3><p>You can use a druidic focus as a spellcasting focus for your druid spells.</p>",
    "lvl2":"<h2 id='WildShape'>Wild Shape</h2><hr><p>Starting at 2nd level, you can use your action to magically assume the shape of a beast that you have seen before. You can use this feature twice. You regain expended uses when you finish a short or long rest.</p><p>Your druid level determines the beasts you can transform into, as shown in the Beast Shapes table. At 2nd level, for example, you can transform into any beast that has hit dice equal to or less than 1 that doesn't have a flying or swimming speed.</p><table><caption>Beast Shapes</caption><tr><th>Level</th><th>Max Hit Dice</th><th>Limitations</th><th>Example</th></tr><tr><td>2nd</td><td>1</td><td>No flying, swimming, or burrow speed</td><td>Wolf Spider, Cat</td></tr><tr><td>4th</td><td>2</td><td>No flying or burrow speed</td><td>Octopus, Wolf</td></tr><tr><td>8th</td><td>3</td><td>No burrow speed</td><td>Large Eagle, Crocodile</td></tr><tr><td>12th</td><td>4</td><td>None</td><td>Huge Mole, Dire Wolf</td></tr><tr><td>16th</td><td>5</td><td>None</td><td>Dire Crocodile, Rhinocerous</td></tr></table><p>You can stay in a beast shape for a number of hours equal to half your druid level (rounded down). You then revert to your normal form unless you expend another use of this feature. You can revert to your normal form earlier by using a bonus action on your turn. You automatically revert if you fall unconscious, drop to 0 hit points, or die.</p><p>While you are transformed, the following rules apply:</p><ul><li>Your game statistics are replaced by the statistics of the beast, but you retain your alignment, personality, and Intelligence, Wisdom, and Charisma scores. You also retain all of your skill and saving throw proficiencies, in addition to gaining those of the creature. If the creature has the same proficiency as you and the bonus in its stat block is higher than yours, use the creature's bonus instead of yours. If the creature has any legendary or lair actions, you can't use them.</li><li>When you transform, you assume the beast's hit points and Hit Dice. When you revert to your normal form, you return to the number of hit points you had before you transformed. However, if you revert as a result of dropping to 0 hit points, any excess damage carries over to your normal form. For example, if you take 10 damage in animal form and have only 1 hit point left, you revert and take 9 damage. As long as the excess damage doesn't reduce your normal form to 0 hit points, you aren't knocked unconscious.</li><li>You can't cast spells, and your ability to speak or take any action that requires hands is limited to the capabilities of your beast form. Transforming doesn't break your concentration on a spell you've already cast, however, or prevent you from taking actions that are part of a spell, such as call lightning, that you've already cast.</li><li>You retain the benefit of any features from your class, race, or other source and can use them if the new form is physically capable of doing so. However, you can't use any of your special senses, such as darkvision, unless your new form also has that sense.</li><li>You choose whether your equipment falls to the ground in your space, merges into your new form, or is worn by it. Worn equipment functions as normal, but the DM decides whether it is practical for the new form to wear a piece of equipment, based on the creature's shape and size. Your equipment doesn't change size or shape to match the new form, and any equipment that the new form can't wear must either fall to the ground or merge with it. Equipment that merges with the form has no effect until you leave the form.</li></ul><h2 id='DruidCircle'>Druid Circle</h2><hr><p>At 2nd level, you choose to identify with a circle of druids from the list of available circles. Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level.</p>",
    "lvl3":"",
    "lvl4":"<h2 id='WildShapeImprovement1'>Wild Shape Improvement</h2><hr><p>At 4th level, your Wild Shape improves as shown on the Beast Shapes table.At 4th level, your Wild Shape improves as shown on the Beast Shapes table.</p>",
    "lvl5":"",
    "lvl6":"<h2 id='DruidCircleFeature1'>Druid Circle Feature</h2><hr><p>At 6th level, you gain a feature granted by your Druid Circle.</p>",
    "lvl7":"",
    "lvl8":"<h2 id='WildShapeImprovement2'>Wild Shape Improvement</h2><hr><p>At 8th level, your Wild Shape improves as shown on the Beast Shapes table.</p>",
    "lvl9":"",
    "lvl10":"<h2 id='DruidCircleFeature2'>Druid Circle Feature</h2><hr><p>At 10th level, you gain a feature granted by your Druid Circle.</p>",
    "lvl11":"",
    "lvl12":"<h2 id='WildShapeImprovement3'>Wild Shape Improvement</h2><hr><p>At 12th level, your Wild Shape improves as shown on the Beast Shapes table.</p>",
    "lvl13":"",
    "lvl14":"<h2 id='DruidCircleFeature3'>Druid Circle Feature</h2><hr><p>At 14th level, you gain a feature granted by your Druid Circle.</p>",
    "lvl15":"",
    "lvl16":"<h2 id='WildShapeImprovement4'>Wild Shape Improvement</h2><hr><p>At 16th level, your Wild Shape improves as shown on the Beast Shapes table.</p>",
    "lvl17":"",
    "lvl18":"<h2 id='TimelessBody'>Timeless Body</h2><hr><p>Starting at 18th level, the primal magic that you wield causes you to age more slowly. For every 10 years that pass, your body ages only 1 year.</p><h2 id='BeastSpells'>Beast Spells</h2><hr><p>Beginning at 18th level, you can cast many of your druid spells in any shape you assume using Wild Shape. You can perform the somatic and verbal components of a druid spell while in a beast shape, but you aren't able to provide material components.</p>",
    "lvl19":"",
    "lvl20":"<h2 id='Archdruid'>Archdruid</h2><hr><p>At 20th level, you can use your Wild Shape an unlimited number of times.</p><p>Additionally, you can ignore the verbal and somatic components of your druid spells, as well as any material components that lack a cost and aren't consumed by a spell. You gain this benefit in both your normal shape and your beast shape from Wild Shape.</p>",
  },
  {
    "name":"Fighter",
    "hitDie":8,
    "hpPerLvl":5,
    "scoreMinimum":"Strength 13 or Dexterity 13.",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Monk",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Dexterity 13 and Wisdom 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Paladin",
    "hitDie":8,
    "hpPerLvl":5,
    "scoreMinimum":"Charisma 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Ranger",
    "hitDie":8,
    "hpPerLvl":5,
    "scoreMinimum":"Wisdom 13 and either Strength 13 or Dexterity 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Rogue",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Dexterity 13 and Intelligence 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Sorcerer",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Charisma 13",
    "otherRequirement":"None.",
    "table":"<colgroup><col style='width:10%;'><col style='width:10%;'><col style='width:22%;'><col style='width:8%;'><col style='width:8%;'><col style='width:8%;'></colgroup><tr><th colspan='6'></th><th colspan='9'><i>Spell Slots per Spell Level</i></th></tr><tr><th>Level</th><th>Proficiency Bonus</th><th>Features</th><th>Sorcery Points</th><th>Cantrips Known</th><th>Spells Known</th><th>1st</th><th>2nd</th><th>3rd</th><th>4th</th><th>5th</th><th>6th</th><th>7th</th><th>8th</th><th>9th</th></tr><tr><td>1st</td><td>+2</td><td><a href='#Spellcasting'>Spellcasting</a>, <a href='#SorcerousOrigin'>Sorcerous Origin</a></td><td>—</td><td>3</td><td>2</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>2nd</td><td>+2</td><td><a href='#FontofMagic'>Font of Magic</a></td><td>2</td><td>3</td><td>3</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>3rd</td><td>+2</td><td><a href='#EnhancedArcana1'>Enhanced Arcana</a></td><td>3</td><td>4</td><td>4</td><td>4</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>4th</td><td>+2</td><td>—</td><td>4</td><td>4</td><td>5</td><td>4</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>5th</td><td>+3</td><td>—</td><td>5</td><td>4</td><td>6</td><td>4</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>6th</td><td>+3</td><td><a href='#SorcerousOriginFeature1'>Sorcerous Origin Feature</a></td><td>6</td><td>4</td><td>7</td><td>4</td><td>3</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>7th</td><td>+3</td><td>—</td><td>7</td><td>4</td><td>8</td><td>4</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>8th</td><td>+3</td><td>—</td><td>8</td><td>4</td><td>9</td><td>4</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>9th</td><td>+4</td><td>—</td><td>9</td><td>4</td><td>10</td><td>4</td><td>3</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>10th</td><td>+4</td><td><a href='#EnhancedArcana2'>Enhanced Arcana</a></td><td>10</td><td>5</td><td>11</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>11th</td><td>+4</td><td>—</td><td>11</td><td>5</td><td>12</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>12th</td><td>+4</td><td>—</td><td>12</td><td>5</td><td>12</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>13th</td><td>+5</td><td>—</td><td>13</td><td>5</td><td>13</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>14th</td><td>+5</td><td><a href='#SorcerousOriginFeature2'>Sorcerous Origin Feature</a></td><td>14</td><td>5</td><td>13</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>15th</td><td>+5</td><td>—</td><td>15</td><td>5</td><td>14</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>16th</td><td>+5</td><td>—</td><td>16</td><td>5</td><td>14</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>17th</td><td>+6</td><td><a href='#EnhancedArcana3'>Enhanced Arcana</a></td><td>17</td><td>5</td><td>15</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>18th</td><td>+6</td><td><a href='#SorcerousOriginFeature3'>Sorcerous Origin Feature</a></td><td>18</td><td>5</td><td>15</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>19th</td><td>+6</td><td>—</td><td>19</td><td>5</td><td>16</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td></tr><tr><td>20th</td><td>+6</td><td><a href='#SorcerousRestoration'>Sorcerous Restoration</a></td><td>20</td><td>5</td><td>17</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>2</td><td>1</td><td>1</td></tr>",
    "subclassList":"<tr><th>Sorcerous Origins</th></tr><tr><td><a href='#' onclick='originDisplay(0)'>Divine Soul</a></td></tr><tr><td><a href='#' onclick='originDisplay(1)'>Draconic Bloodline</a></td></tr><tr><td><a href='#' onclick='originDisplay(2)'>Shadow Magic</a></td></tr><tr><td><a href='#' onclick='originDisplay(3)'>Star Touched</a></td></tr><tr><td><a href='#' onclick='originDisplay(4)'>Storm Sorcery</a></td></tr>",
    "lvl1":"<h2 id='Spellcasting'>Spellcasting</h2><hr><p>An event in your past, or in the life of a parent or ancestor, left an indelible mark on you, infusing you with arcane magic.</p><h3>Cantrips</h3><p>At 1st level, you know four cantrips of your choice from the sorcerer spell list. You learn an additional sorcerer cantrip of your choice at 4th level and another at 10th level.</p><h3>Spell Slots</h3><p>The Sorcerer table shows how many spell slots you have to cast your sorcerer spells of 1st level and higher. To cast one of these sorcerer spells, you must expend a slot of the spell's level or higher. You regain all expended spell slots when you finish a long rest.</p><p>For example, if you know the 1st-level spell burning hands and have a 1st-level and a 2nd-level spell slot available, you can cast burning hands using either slot.</p><h3>Spells Known of 1st Level and Higher</h3><p>You know two 1st-level spells of your choice from the sorcerer spell list.</p><p>You learn an additional sorcerer spell of your choice at each level except 12th, 14th, 16th, 18th, 19th, and 20th. Each of these spells must be of a level for which you have spell slots. For instance, when you reach 3rd level in this class, you can learn one new spell of 1st or 2nd level.</p><p>Additionally, when you gain a level in this class, you can choose one of the sorcerer spells you know and replace it with another spell from the sorcerer spell list, which also must be of a level for which you have spell slots.</p><h3>Spellcasting Ability</h3><p>Charisma is your spellcasting ability for your sorcerer spells, since the power of your magic relies on your ability to project your will into the world. You use your Charisma whenever a spell refers to your spellcasting ability. In addition, you use your Charisma modifier when setting the saving throw DC for a sorcerer spell you cast and when making an attack roll with one.</p><ul><li><strong>Spell Save DC</strong> = 8 + your proficiency bonus + your Charisma modifier</li><li><strong>Spell Attack Modifier</strong> = your proficiency bonus + your Charisma modifier</li></ul><h2 id='SorcerousOrigin'>Sorcerous Origin</h2><hr><p>Choose a sorcerous origin, which describes the source of your innate magical power, from the list of available origins.</p><p>Your choice grants you features when you choose it at 1st level and again at 6th, 14th, and 18th level.</p>",
    "lvl2":"<h2 id='FontofMagic'>Font of Magic</h2><hr><p>At 2nd level, you tap into a deep wellspring of magic within yourself. This wellspring is represented by sorcery points, which allow you to create a variety of magical effects.</p><h3>Sorcery Points</h3><p>You have 2 sorcery points, and you gain one additional point every time you level up, to a maximum of 20 at level 20. You can never have more sorcery points than shown on the table for your level. You regain all spent sorcery points when you finish an extended rest.</p><h3>Flexible Casting</h3><p>You can use your sorcery points to gain additional spell slots, or sacrifice spell slots to gain additional sorcery points. You learn other ways to use your sorcery points as you reach higher levels.</p><p><strong>Creating Spell Slots.</strong> You can transform unexpended sorcery points into one spell slot as a bonus action on your turn. The created spell slots vanish at the end of a long rest. The Creating Spell Slots table shows the cost of creating a spell slot of a given level. You can create spell slots no higher in level than 5th.</p><table><caption>Creating Spell Slots</caption><tr><th>Spell Slot Level</th><th>Sorcery Points Spent</th></tr><tr><td>1st</td><td>2</td></tr><tr><td>2nd</td><td>3</td></tr><tr><td>3rd</td><td>5</td></tr><tr><td>4th</td><td>6</td></tr><tr><td>5th</td><td>7</td></tr></table><p><strong>Converting a Spell Slot to Sorcery Points.</strong> As a bonus action on your turn, you can expend one spell slot and gain a number of sorcery points equal to the slot's level.</p>",
    "lvl3":"<h2 id='EnhancedArcana1'>Enhanced Arcana</h2><hr><p>At 3rd level, your wellspring of magic becomes rife with arcane power. You gain 3 boon points, which you may spend only on Spell Augmentations or Spellcasting Boons. When you gain a level in this class, you may choose to replace any spent Enhanced Arcana boon points with other Spell Augmentations or Spellcasting Boons.</p>",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"<h2 id='SorcerousOriginFeature1'>Sorcerous Origin Feature</h2><hr><p>At 6th level, you gain a feature granted by your Sorcerous Origin.</p>",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"<h2 id='EnhancedArcana2'>Enhanced Arcana</h2><hr><p>At 10th level, you gain an additional 4 Enhanced Arcana points.</p>",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"<h2 id='SorcerousOriginFeature2'>Sorcerous Origin Feature</h2><hr><p>At 14th level, you gain a feature granted by your Sorcerous Origin.</p>",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"<h2 id='EnhancedArcana3'>Enhanced Arcana</h2><hr><p>At 17th level, you gain an additional 5 Enhanced Arcana points.</p>",
    "lvl18":"<h2 id='SorcerousOriginFeature3'>Sorcerous Origin Feature</h2><hr><p>At 18th level, you gain a feature granted by your Sorcerous Origin.</p>",
    "lvl19":"",
    "lvl20":"<h2 id='SorcerousRestoration'>Sorcerous Restoration</h2><hr><p>When you finish a long rest, restore all expended spell slots.</p>",
  },
  {
    "name":"Warlock",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Charisma 13 and Constitution 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Wizard",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Intelligence 13",
    "otherRequirement":"Proficiency with the Arcana skill.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  }
];
