var c1 = [
  {
    "name":"Barbarian",
    "hitDie":10,
    "hpPerLvl":6,
    "scoreMinimum":"Constitution 13",
    "otherRequirement":"None.",
    "table":"<colgroup><col style='width:10%;'><col style='width:10%;'><col style='width:60%;'><col style='width:10%;'><col style='width:10%;'></colgroup><tr><th>Level</th><th>Proficiency Bonus</th><th>Features</th><th>Rages</th><th>Rage Damage</th></tr><tr><td>1st</td><td>+2</td><td><a href='#Barbarian,Rage'>Rage</a>, <a href='#Barbarian,UnarmoredDefense'>Unarmored Defense</a></td><td>2</td><td>+2</td></tr><tr><td>2nd</td><td>+2</td><td><a href='#Barbarian,DangerSense'>Danger Sense</a>, <a href='#Barbarian,RecklessAttack'>Reckless Attack</a></td><td>2</td><td>+2</td></tr><tr><td>3rd</td><td>+2</td><td><a href='#Barbarian,PrimalPath'>Primal Path</a></td><td>3</td><td>+2</td></tr><tr><td>4th</td><td>+2</td><td>—</td><td>3</td><td>+2</td></tr><tr><td>5th</td><td>+3</td><td><a href='#Barbarian,ExtraAttack'>Extra Attack</a>, <a href='#Barbarian,FastMovement'>Fast Movement</a></td><td>3</td><td>+2</td></tr><tr><td>6th</td><td>+3</td><td><a href='#Barbarian,PathFeature1'>Path Feature</a></td><td>4</td><td>+2</td></tr><tr><td>7th</td><td>+3</td><td><a href='#Barbarian,FeralInstinct'>Feral Instinct</a></td><td>4</td><td>+2</td></tr><tr><td>8th</td><td>+3</td><td>—</td><td>4</td><td>+2</td></tr><tr><td>9th</td><td>+4</td><td><a href='#Barbarian,BrutalCritical1'>Brutal Critical (1 die)</a></td><td>4</td><td>+3</td></tr><tr><td>10th</td><td>+4</td><td><a href='#Barbarian,PathFeature2'>Path Feature</a></td><td>4</td><td>+3</td></tr><tr><td>11th</td><td>+4</td><td><a href='#Barbarian,RelentlessRage'>Relentless Rage</a></td><td>4</td><td>+3</td></tr><tr><td>12th</td><td>+4</td><td>—</td><td>5</td><td>+3</td></tr><tr><td>13th</td><td>+5</td><td><a href='#Barbarian,BrutalCritical2'>Brutal Critical (2 dice)</a></td><td>5</td><td>+3</td></tr><tr><td>14th</td><td>+5</td><td><a href='#Barbarian,PathFeature3'>Path Feature</a></td><td>5</td><td>+3</td></tr><tr><td>15th</td><td>+5</td><td><a href='#Barbarian,PersistentRage'>Persistent Rage</a></td><td>5</td><td>+3</td></tr><tr><td>16th</td><td>+5</td><td>—</td><td>5</td><td>+4</td></tr><tr><td>17th</td><td>+6</td><td><a href='#Barbarian,BrutalCritical3'>Brutal Critical (3 dice)</a></td><td>6</td><td>+4</td></tr><tr><td>18th</td><td>+6</td><td><a href='#Barbarian,IndomitableMight'>Indomitable Might</a></td><td>6</td><td>+4</td></tr><tr><td>19th</td><td>+6</td><td>—</td><td>6</td><td>+4</td></tr><tr><td>20th</td><td>+6</td><td><a href='#Barbarian,PrimalChampion'>Primal Champion</a></td><td>Unlimited</td><td>+4</td></tr>",
    "subclassList":"<tr><th>Primal Paths</th></tr><tr><td><a href='#' onclick='pathDisplay(0)'>Ancestral Guardian</a></td></tr></tr><tr><td><a href='#' onclick='pathDisplay(1)'>Berserker</a></td></tr><tr><td><a href='#' onclick='pathDisplay(2)'>Storm Herald</a></td></tr><tr><td><a href='#' onclick='pathDisplay(3)'>Totem Warrior</a></td></tr><tr><td><a href='#' onclick='pathDisplay(4)'>Zealot</a></td></tr>",
    "lvl1":"<h2 id='Barbarian,Rage'>Rage</h2><hr><p>In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action. While raging, you gain the following benefits if you aren't wearing heavy armor:</p><ul><li>You have advantage on Strength checks and Strength saving throws.</li><li>When you make a melee weapon attack using Strength, you gain a +2 bonus to the damage roll. This bonus increases as you level.</li><li>You have resistance to bludgeoning, piercing, and slashing damage.</li></ul><p>If you are able to cast spells, you can't cast them or concentrate on them while raging.</p><p>Your rage lasts for 1 minute. It ends early if you are knocked unconscious or if your turn ends and you haven't attacked a hostile creature since your last turn or taken damage since then. You can also end your rage on your turn as a bonus action.</p><p>Once you have raged the maximum number of times for your barbarian level, you must finish a long rest before you can rage again. You may rage 2 times at 1st level, 3 at 3rd, 4 at 6th, 5 at 12th, and 6 at 17th.</p><h2 id='Barbarian,UnarmoredDefense'>Unarmored Defense</h2><hr><p>While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit.</p>",
    "lvl2":"<h2 id='Barbarian,DangerSense'>Danger Sense</h2><hr><p>At 2nd level, you gain an uncanny sense of when things nearby aren't as they should be, giving you an edge when you dodge away from danger. You have advantage on Dexterity saving throws against effects that you can see, such as traps and spells. To gain this benefit, you can't be blinded, deafened, or incapacitated.</p><h2 id='Barbarian,RecklessAttack'>Reckless Attack</h2><hr><p>Starting at 2nd level, you can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly. Doing so gives you advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn.</p>",
    "lvl3":"<h2 id='Barbarian,PrimalPath'>Primal Path</h2><hr><p>At 3rd level, you choose a path that shapes the nature of your rage from the list of available paths. Your choice grants you features at 3rd level and again at 6th, 10th, and 14th levels.</p>",
    "lvl4":"",
    "lvl5":"<h2 id='Barbarian,ExtraAttack'>Extra Attack</h2><hr><p>Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.</p><h2 id='Barbarian,FastMovement'>Fast Movement</h2><hr><p>Starting at 5th level, your speed increases by 3 meters while you aren't wearing heavy armor.</p>",
    "lvl6":"<h2 id='Barbarian,PathFeature1'>Path Feature</h2><hr><p>At 6th level, you gain a feature from your Primal Path.</p>",
    "lvl7":"<h2 id='Barbarian,FeralInstinct'>Feral Instinct</h2><hr><p>By 7th level, your instincts are so honed that you have advantage on initiative rolls.</p><p>Additionally, if you are surprised at the beginning of combat and aren't incapacitated, you can act normally on your first turn, but only if you enter your rage before doing anything else on that turn.</p>",
    "lvl8":"",
    "lvl9":"<h2 id='Barbarian,BrutalCritical1'>Brutal Critical (1 die)</h2><hr><p>Beginning at 9th level, you can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack.</p><p>This increases to two additional dice at 13th level and three additional dice at 17th level.</p>",
    "lvl10":"<h2 id='Barbarian,PathFeature2'>Path Feature</h2><hr><p>At 10th level, you gain a feature from your Primal Path.</p>",
    "lvl11":"<h2 id='Barbarian,RelentlessRage'>Relentless Rage</h2><hr><p>Starting at 11th level, your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while you're raging and don't die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead.</p><p>Each time you use this feature after the first, the DC increases by 5. When you finish a short or long rest, the DC resets to 10.</p>",
    "lvl12":"",
    "lvl13":"<h2 id='Barbarian,BrutalCritical2'>Brutal Critical (2 dice)</h2><hr><p>At 13th level, you can roll two additional weapon damage dice when determining the extra damage for a critical hit with a melee attack.</p><p>This increases to three additional dice at 17th level.</p>",
    "lvl14":"<h2 id='Barbarian,PathFeature3'>Path Feature</h2><hr><p>At 14th level, you gain a feature from your Primal Path.</p>",
    "lvl15":"<h2 id='Barbarian,PersistentRage'>Persistent Rage</h2><hr><p>Beginning at 15th level, your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it.</p>",
    "lvl16":"",
    "lvl17":"<h2 id='Barbarian,BrutalCritical3'>Brutal Critical (3 dice)</h2><hr><p>At 17th level, you can roll three additional weapon damage dice when determining the extra damage for a critical hit with a melee attack.</p>",
    "lvl18":"<h2 id='Barbarian,IndomitableMight'>Indomitable Might</h2><hr><p>Beginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total.</p>",
    "lvl19":"",
    "lvl20":"<h2 id='Barbarian,PrimalChampion'>Primal Champion</h2><hr><p>At 20th level, you embody the power of the wilds. Your Strength and Constitution scores, along with their maximum, increase by 4. </p>",

  },
  {
    "name":"Bard",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Charisma 13",
    "otherRequirement":"Proficiency with the Performance skill.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Cleric",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Wisdom 13",
    "otherRequirement":"Proficiency with the Divina skill.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Druid",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Wisdom 13",
    "otherRequirement":"Proficiency with the Prima skill.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Fighter",
    "hitDie":8,
    "hpPerLvl":5,
    "scoreMinimum":"Strength 13 or Dexterity 13.",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Monk",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Dexterity 13 and Wisdom 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Paladin",
    "hitDie":8,
    "hpPerLvl":5,
    "scoreMinimum":"Charisma 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Ranger",
    "hitDie":8,
    "hpPerLvl":5,
    "scoreMinimum":"Wisdom 13 and either Strength 13 or Dexterity 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Rogue",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Dexterity 13 and Intelligence 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Sorcerer",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Charisma 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Warlock",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Charisma 13 and Constitution 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Wizard",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Intelligence 13",
    "otherRequirement":"Proficiency with the Arcana skill.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  }
];
