var c1 = [
  {
    "name":"Barbarian",
    "hitDie":10,
    "hpPerLvl":6,
    "scoreMinimum":"Constitution 13",
    "otherRequirement":"None.",
    "table":"<colgroup><col style='width:10%;'><col style='width:10%;'><col style='width:60%;'><col style='width:10%;'><col style='width:10%;'></colgroup><tr><th>Level</th><th>Proficiency Bonus</th><th>Features</th><th>Rages</th><th>Rage Damage</th></tr><tr><td>1st</td><td>+2</td><td><a href='#Rage'>Rage</a>, <a href='#UnarmoredDefense'>Unarmored Defense</a></td><td>2</td><td>+2</td></tr><tr><td>2nd</td><td>+2</td><td><a href='#DangerSense'>Danger Sense</a>, <a href='#RecklessAttack'>Reckless Attack</a></td><td>2</td><td>+2</td></tr><tr><td>3rd</td><td>+2</td><td><a href='#PrimalPath'>Primal Path</a></td><td>3</td><td>+2</td></tr><tr><td>4th</td><td>+2</td><td>—</td><td>3</td><td>+2</td></tr><tr><td>5th</td><td>+3</td><td><a href='#ExtraAttack'>Extra Attack</a>, <a href='#FastMovement'>Fast Movement</a></td><td>3</td><td>+2</td></tr><tr><td>6th</td><td>+3</td><td><a href='#PathFeature1'>Path Feature</a></td><td>4</td><td>+2</td></tr><tr><td>7th</td><td>+3</td><td><a href='#FeralInstinct'>Feral Instinct</a></td><td>4</td><td>+2</td></tr><tr><td>8th</td><td>+3</td><td>—</td><td>4</td><td>+2</td></tr><tr><td>9th</td><td>+4</td><td><a href='#BrutalCritical1'>Brutal Critical (1 die)</a></td><td>4</td><td>+3</td></tr><tr><td>10th</td><td>+4</td><td><a href='#PathFeature2'>Path Feature</a></td><td>4</td><td>+3</td></tr><tr><td>11th</td><td>+4</td><td><a href='#RelentlessRage'>Relentless Rage</a></td><td>4</td><td>+3</td></tr><tr><td>12th</td><td>+4</td><td>—</td><td>5</td><td>+3</td></tr><tr><td>13th</td><td>+5</td><td><a href='#BrutalCritical2'>Brutal Critical (2 dice)</a></td><td>5</td><td>+3</td></tr><tr><td>14th</td><td>+5</td><td><a href='#PathFeature3'>Path Feature</a></td><td>5</td><td>+3</td></tr><tr><td>15th</td><td>+5</td><td><a href='#PersistentRage'>Persistent Rage</a></td><td>5</td><td>+3</td></tr><tr><td>16th</td><td>+5</td><td>—</td><td>5</td><td>+4</td></tr><tr><td>17th</td><td>+6</td><td><a href='#BrutalCritical3'>Brutal Critical (3 dice)</a></td><td>6</td><td>+4</td></tr><tr><td>18th</td><td>+6</td><td><a href='#IndomitableMight'>Indomitable Might</a></td><td>6</td><td>+4</td></tr><tr><td>19th</td><td>+6</td><td>—</td><td>6</td><td>+4</td></tr><tr><td>20th</td><td>+6</td><td><a href='#PrimalChampion'>Primal Champion</a></td><td>Unlimited</td><td>+4</td></tr>",
    "subclassList":"<tr><th>Primal Paths</th></tr><tr><td><a href='#' onclick='pathDisplay(0)'>Ancestral Guardian</a></td></tr></tr><tr><td><a href='#' onclick='pathDisplay(1)'>Berserker</a></td></tr><tr><td><a href='#' onclick='pathDisplay(2)'>Storm Herald</a></td></tr><tr><td><a href='#' onclick='pathDisplay(3)'>Totem Warrior</a></td></tr><tr><td><a href='#' onclick='pathDisplay(4)'>Zealot</a></td></tr>",
    "lvl1":"<h2 id='Rage'>Rage</h2><hr><p>In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action. While raging, you gain the following benefits if you aren't wearing heavy armor:</p><ul><li>You have advantage on Strength checks and Strength saving throws.</li><li>When you make a melee weapon attack using Strength, you gain a +2 bonus to the damage roll. This bonus increases as you level.</li><li>You have resistance to bludgeoning, piercing, and slashing damage.</li></ul><p>If you are able to cast spells, you can't cast them or concentrate on them while raging.</p><p>Your rage lasts for 1 minute. It ends early if you are knocked unconscious or if your turn ends and you haven't attacked a hostile creature since your last turn or taken damage since then. You can also end your rage on your turn as a bonus action.</p><p>Once you have raged the maximum number of times for your barbarian level, you must finish a long rest before you can rage again. You may rage 2 times at 1st level, 3 at 3rd, 4 at 6th, 5 at 12th, and 6 at 17th.</p><h2 id='UnarmoredDefense'>Unarmored Defense</h2><hr><p>While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit.</p>",
    "lvl2":"<h2 id='DangerSense'>Danger Sense</h2><hr><p>At 2nd level, you gain an uncanny sense of when things nearby aren't as they should be, giving you an edge when you dodge away from danger. You have advantage on Dexterity saving throws against effects that you can see, such as traps and spells. To gain this benefit, you can't be blinded, deafened, or incapacitated.</p><h2 id='RecklessAttack'>Reckless Attack</h2><hr><p>Starting at 2nd level, you can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly. Doing so gives you advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn.</p>",
    "lvl3":"<h2 id='PrimalPath'>Primal Path</h2><hr><p>At 3rd level, you choose a path that shapes the nature of your rage from the list of available paths. Your choice grants you features at 3rd level and again at 6th, 10th, and 14th levels.</p>",
    "lvl4":"",
    "lvl5":"<h2 id='ExtraAttack'>Extra Attack</h2><hr><p>Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.</p><h2 id='FastMovement'>Fast Movement</h2><hr><p>Starting at 5th level, your speed increases by 3 meters while you aren't wearing heavy armor.</p>",
    "lvl6":"<h2 id='PathFeature1'>Path Feature</h2><hr><p>At 6th level, you gain a feature from your Primal Path.</p>",
    "lvl7":"<h2 id='FeralInstinct'>Feral Instinct</h2><hr><p>By 7th level, your instincts are so honed that you have advantage on initiative rolls.</p><p>Additionally, if you are surprised at the beginning of combat and aren't incapacitated, you can act normally on your first turn, but only if you enter your rage before doing anything else on that turn.</p>",
    "lvl8":"",
    "lvl9":"<h2 id='BrutalCritical1'>Brutal Critical (1 die)</h2><hr><p>Beginning at 9th level, you can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack.</p><p>This increases to two additional dice at 13th level and three additional dice at 17th level.</p>",
    "lvl10":"<h2 id='PathFeature2'>Path Feature</h2><hr><p>At 10th level, you gain a feature from your Primal Path.</p>",
    "lvl11":"<h2 id='RelentlessRage'>Relentless Rage</h2><hr><p>Starting at 11th level, your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while you're raging and don't die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead.</p><p>Each time you use this feature after the first, the DC increases by 5. When you finish a short or long rest, the DC resets to 10.</p>",
    "lvl12":"",
    "lvl13":"<h2 id='BrutalCritical2'>Brutal Critical (2 dice)</h2><hr><p>At 13th level, you can roll two additional weapon damage dice when determining the extra damage for a critical hit with a melee attack.</p><p>This increases to three additional dice at 17th level.</p>",
    "lvl14":"<h2 id='PathFeature3'>Path Feature</h2><hr><p>At 14th level, you gain a feature from your Primal Path.</p>",
    "lvl15":"<h2 id='PersistentRage'>Persistent Rage</h2><hr><p>Beginning at 15th level, your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it.</p>",
    "lvl16":"",
    "lvl17":"<h2 id='BrutalCritical3'>Brutal Critical (3 dice)</h2><hr><p>At 17th level, you can roll three additional weapon damage dice when determining the extra damage for a critical hit with a melee attack.</p>",
    "lvl18":"<h2 id='IndomitableMight'>Indomitable Might</h2><hr><p>Beginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total.</p>",
    "lvl19":"",
    "lvl20":"<h2 id='PrimalChampion'>Primal Champion</h2><hr><p>At 20th level, you embody the power of the wilds. Your Strength and Constitution scores, along with their maximum, increase by 4. </p>",

  },
  {
    "name":"Bard",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Charisma 13",
    "otherRequirement":"Proficiency with the Performance skill.",
    "table":"<colgroup><col style='width:10%;'><col style='width:10%;'><col style='width:30%;'><col style='width:8%;'><col style='width:8%;'></colgroup><tr><th colspan='5'></th><th colspan='9'><i>Spell Slots per Spell Level</i></th></tr><tr><th>Level</th><th>Proficiency Bonus</th><th>Features</th><th>Cantrips Known</th><th>Spells Known</th><th>1st</th><th>2nd</th><th>3rd</th><th>4th</th><th>5th</th><th>6th</th><th>7th</th><th>8th</th><th>9th</th></tr><tr><td>1st</td><td>+2</td><td><a href='#BardicInspiration1'>Bardic Inspiration (d6)</a>, <a href='#Spellcasting'>Spellcasting</a></td><td>2</td><td>4</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>2nd</td><td>+2</td><td><a href='#JackofAllTrades'>Jack of All Trades</a>, <a href='#SongofRest1'>Song of Rest (d6)</a></td><td>2</td><td>5</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>3rd</td><td>+2</td><td><a href='#BardCollege'>Bard College</a></td><td>2</td><td>6</td><td>4</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>4th</td><td>+2</td><td>—</td><td>3</td><td>7</td><td>4</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>5th</td><td>+3</td><td><a href='#BardicInspiration2'>Bardic Inspiration (d8)</a></td><td>3</td><td>8</td><td>4</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>6th</td><td>+3</td><td><a href='#Countercharm'>Countercharm</a>, <a href='#BardCollegeFeature1'>Bard College Feature</a></td><td>3</td><td>9</td><td>4</td><td>3</td><td>3</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>7th</td><td>+3</td><td>—</td><td>3</td><td>10</td><td>4</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>8th</td><td>+3</td><td>—</td><td>3</td><td>11</td><td>4</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>9th</td><td>+4</td><td><a href='#SongofRest2'>Song of Rest (1d8)</a></td><td>3</td><td>12</td><td>4</td><td>3</td><td>3</td><td>3</td><td>1</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>10th</td><td>+4</td><td><a href='#BardicInspiration3'>Bardic Inspiration (d10)</a>, <a href='#Expertise2'>Expertise</a>, <a href='#MagicalSecrets1'>Magical Secrets</a></td><td>4</td><td>14</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td><td>—</td></tr><tr><td>11th</td><td>+4</td><td>—</td><td>4</td><td>15</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>12th</td><td>+4</td><td>—</td><td>4</td><td>15</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>—</td><td>—</td><td>—</td></tr><tr><td>13th</td><td>+5</td><td><a href='#SongofRest3'>Song of Rest (d10)</a></td><td>4</td><td>16</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>14th</td><td>+5</td><td><a href='#MagicalSecrets2'>Magical Secrets</a>, <a href='#BardCollegeFeature2'>Bard College Feature</a></td><td>4</td><td>18</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>—</td><td>—</td></tr><tr><td>15th</td><td>+5</td><td><a href='#BardicInspiration4'>Bardic Inspiration (d12)</a></td><td>4</td><td>19</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>16th</td><td>+5</td><td>—</td><td>4</td><td>19</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>—</td></tr><tr><td>17th</td><td>+6</td><td><a href='#SongofRest4'>Song of Rest (d12)</a></td><td>4</td><td>20</td><td>4</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>18th</td><td>+6</td><td><a href='#MagicalSecrets3'>Magical Secrets</a></td><td>4</td><td>22</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>1</td><td>1</td><td>1</td><td>1</td></tr><tr><td>19th</td><td>+6</td><td>—</td><td>4</td><td>22</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>1</td><td>1</td><td>1</td></tr><tr><td>20th</td><td>+6</td><td><a href='#SuperiorInspiration'>Superior Inspiration</a></td><td>4</td><td>22</td><td>4</td><td>3</td><td>3</td><td>3</td><td>3</td><td>2</td><td>2</td><td>1</td><td>1</td></tr>",
    "subclassList":"<tr><th>Bard Colleges</th></tr><tr><td><a href='#' onclick='collegeDisplay(0)'>Eloquence</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(1)'>Glamour</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(2)'>Lore</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(3)'>Swords</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(4)'>Valor</a></td></tr><tr><td><a href='#' onclick='collegeDisplay(5)'>Whispers</a></td></tr>",
    "lvl1":"<h2 id='BardicInspiration1'>Bardic Inspiration (d6)</h2><hr><p>You can inspire others through stirring words or music. To do so, you use a bonus action on your turn to choose one creature other than yourself within 20 meters of you who can hear you. That creature gains one Bardic Inspiration die, a d6.</p><p>Once within the next 10 minutes, the creature can roll the die and add the number rolled to one ability check, attack roll, or saving throw it makes. The creature can wait until after it rolls the d20 before deciding to use the Bardic Inspiration die, but must decide before the DM says whether the roll succeeds or fails. Once the Bardic Inspiration die is rolled, it is lost. A creature can have only one Bardic Inspiration die at a time.</p><p>You can use this feature a number of times equal to your Charisma modifier (a minimum of once). You regain any expended uses when you finish a long rest.</p><p>Your Bardic Inspiration die changes when you reach certain levels in this class. The die becomes a d8 at 5th level, a d10 at 10th level, and a d12 at 15th level.</p><h2 id='Spellcasting'>Spellcasting</h2><hr><p>You have learned to untangle and reshape the fabric of reality in harmony with your wishes and music. Your spells are part of your vast repertoire, magic that you can tune to different situations.</p><h3>Cantrips</h3><p>You know two cantrips of your choice from the bard spell list. You learn additional bard cantrips of your choice at higher levels, learning a 3rd cantrip at 4th level and a 4th at 10th level.</p><h3>Spell Slots</h3><p>The Bard table shows how many spell slots you have to cast your bard spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell's level or higher. You regain all expended spell slots when you finish a long rest.</p><p>For example, if you know the 1st-level spell cure wounds and have a 1st-level and a 2nd-level spell slot available, you can cast cure wounds using either slot.</p><h3>Spells Known of 1st Level and Higher</h3><p>You know four 1st-level spells of your choice from the bard spell list.</p><p>You learn an additional bard spell of your choice at each level except 12th, 16th, 19th, and 20th. Each of these spells must be of a level for which you have spell slots. For instance, when you reach 3rd level in this class, you can learn one new spell of 1st or 2nd level.</p><p>Additionally, when you gain a level in this class, you can choose one of the bard spells you know and replace it with another spell from the bard spell list, which also must be of a level for which you have spell slots.</p><h3>Spellcasting Ability</h3><p>Charisma is your spellcasting ability for your bard spells. Your magic comes from the heart and soul you pour into the performance of your music or oration. You use your Charisma whenever a spell refers to your spellcasting ability. In addition, you use your Charisma modifier when setting the saving throw DC for a bard spell you cast and when making an attack roll with one.</p><ul> <li><strong>Spell save DC</strong> = 8 + your proficiency bonus + your Charisma modifier.</li><li><strong>Spell attack modifier</strong> = your proficiency bonus + your Charisma modifier</p></li></ul><h3>Ritual Casting</h3><p>You can cast any bard spell you know as a ritual if that spell has the ritual tag.</p><h3>Spellcasting Focus</h3><p>You can use a musical instrument as a spellcasting focus for your bard spells.</p>",
    "lvl2":"<h2 id='JackofAllTrades'>Jack of All Trades</h2><hr><p>Starting at 2nd level, you can add half your proficiency bonus, rounded down, to any ability check you make that doesn't already include your proficiency bonus.</p><h2 id='SongofRest1'>Song of Rest (d6)</h2><hr><p>Beginning at 2nd level, you can use soothing music or oration to help revitalize your wounded allies during a short rest. If you or any friendly creatures who can hear your performance regain hit points by spending Hit Dice at the end of the short rest, each of those creatures regains an extra 1d6 hit points.</p><p>The extra hit points increase when you reach certain levels in this class: to 1d8 at 9th level, to 1d10 at 13th level, and to 1d12 at 17th level.</p>",
    "lvl3":"<h2 id='BardCollege'>Bard College</h2><hr><p>At 3rd level, you delve into the advanced techniques of a bard college of your choice from the list of available colleges. Your choice grants you features at 3rd level and again at 6th and 14th level.</p><h2 id='Expertise1'>Expertise</h2><hr><p>At 3rd level, choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.</p><p>At 10th level, you can choose another two skill proficiencies to gain this benefit.</p>",
    "lvl4":"",
    "lvl5":"<h2 id='BardicInspiration2'>Bardic Inspiration (d8)</h2><hr><p>At 5th level, your Bardic Inspiration die changes to a d8.</p>",
    "lvl6":"<h2 id='Countercharm'>Countercharm</h2><hr><p>At 6th level, you gain the ability to use musical notes or words of power to disrupt mind-influencing effects. As an action, you can start a performance that lasts until the end of your next turn. During that time, you and any friendly creatures within 10 meters of you have advantage on saving throws against being frightened or charmed. A creature must be able to hear you to gain this benefit. The performance ends early if you are incapacitated or silenced or if you voluntarily end it (no action required).</p><h2 id='BardCollegeFeature1'>Bard College Feature</h2><hr><p>At 6th level, you gain a feature from your Bard College.</p>",
    "lvl7":"<h2 id='FontofInspiration'>Font of Inspiration</h2><hr><p>Starting at 7th level, you gain back one expended use of Bardic Inspiration when you finish a short rest.</p>",
    "lvl8":"",
    "lvl9":"<h2 id='SongofRest2'>Song of Rest (d8)</h2><hr><p>At 9th level, the extra hit points gained from Song of Rest increases to 1d8.</p>",
    "lvl10":"<h2 id='BardicInspiration3'>Bardic Inspiration (d10)</h2><hr><p>At 10th level, your Bardic Inspiration die changes to a d10.</p><h2 id='Expertise2'>Expertise</h2><hr><p>At 10th level, you can choose another two skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.</p><h2 id='MagicalSecrets1'>Magical Secrets</h2><hr><p>By 10th level, you have plundered magical knowledge from a wide spectrum of disciplines. Choose two spells from any classes, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip.</p><p>The chosen spells count as bard spells for you and are included in the number in the Spells Known column of the Bard table.</p><p>You learn two additional spells from any classes at 14th level and again at 18th level.</p>",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"<h2 id='SongofRest3'>Song of Rest (d10)</h2><hr><p>At 13th level, the extra hit points gained from Song of Rest increases to 1d10.</p>",
    "lvl14":"<h2 id='MagicalSecrets2'>Magical Secrets</h2><hr><p>At 14th level, choose two additional spells from any classes, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip.</p><p>The chosen spells count as bard spells for you and are included in the number in the Spells Known column of the Bard table.</p><h2 id='BardCollegeFeature2'>Bard College Feature</h2><hr><p>At 14th level, you gain a feature from your Bard College.</p>",
    "lvl15":"<h2 id='BardicInspiration4'>Bardic Inspiration</h2><hr><p>At 15th level, your Bardic Inspiration die changes to a d12.</p>",
    "lvl16":"",
    "lvl17":"<h2 id='SongofRest4'>Song of Rest (d12)</h2><hr><p>At 17th level, the extra hit points gained from Song of Rest increases to 1d12.</p>",
    "lvl18":"<h2 id='MagicalSecrets3'>Magical Secrets</h2><hr><p>At 18th level, choose two additional spells from any class, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip.</p><p>The chosen spells count as bard spells for you and are included in the number in the Spells Known column of the Bard table.</p>",
    "lvl19":"",
    "lvl20":"<h2 id='SuperiorInspiration'>Superior Inspiration</h2><hr><p>At 20th level, your inspiring nature fully manifests. When a creature uses your Bardic Inspiration die, the lowest number they can roll on it is equal to your Charisma modifier.</p>",
  },
  {
    "name":"Cleric",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Wisdom 13",
    "otherRequirement":"Proficiency with the Divina skill.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Druid",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Wisdom 13",
    "otherRequirement":"Proficiency with the Prima skill.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Fighter",
    "hitDie":8,
    "hpPerLvl":5,
    "scoreMinimum":"Strength 13 or Dexterity 13.",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Monk",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Dexterity 13 and Wisdom 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Paladin",
    "hitDie":8,
    "hpPerLvl":5,
    "scoreMinimum":"Charisma 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Ranger",
    "hitDie":8,
    "hpPerLvl":5,
    "scoreMinimum":"Wisdom 13 and either Strength 13 or Dexterity 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Rogue",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Dexterity 13 and Intelligence 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Sorcerer",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Charisma 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Warlock",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Charisma 13 and Constitution 13",
    "otherRequirement":"None.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  },
  {
    "name":"Wizard",
    "hitDie":6,
    "hpPerLvl":4,
    "scoreMinimum":"Intelligence 13",
    "otherRequirement":"Proficiency with the Arcana skill.",
    "table":"WIP",
    "subclassList":"",
    "lvl1":"",
    "lvl2":"",
    "lvl3":"",
    "lvl4":"",
    "lvl5":"",
    "lvl6":"",
    "lvl7":"",
    "lvl8":"",
    "lvl9":"",
    "lvl10":"",
    "lvl11":"",
    "lvl12":"",
    "lvl13":"",
    "lvl14":"",
    "lvl15":"",
    "lvl16":"",
    "lvl17":"",
    "lvl18":"",
    "lvl19":"",
    "lvl20":"",
  }
];
